### ISSUE TITLE
Enrichment input getting read multiple times

### ISSUE THREAD

**Issue by Alex-Ikanow** [IKANOW/Aleph2#90]
Important bit is `XxxxxxXxxxxxxValidEmailAddresses_With_doEmailValidation_Column_and_md5.json8f06eded-48a2-46df-8626-3e1386e02ab20e02dc27-91f5-4017-a178-53b776e945760ecb6243-edde-4d4d-b343-42934ae30350eba3ea73-f223-4dbf-8890-adbff2cd42c0966ec4ca-d792-4211-b3e0-4657a90b54326592fbba-f195-4145-b069-43faf57bf7e5 in directory /app/aleph2/data/ttm/master/managed_bucket/import/ready/`

    2016-04-29 17:06:23,237 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.protocol.FSLimitException$PathComponentTooLongException): The maximum path component name limit of XxxxxxXxxxxxxValidEmailAddresses_With_doEmailValidation_Column_and_md5.json8f06eded-48a2-46df-8626-3e1386e02ab20e02dc27-91f5-4017-a178-53b776e945760ecb6243-edde-4d4d-b343-42934ae30350eba3ea73-f223-4dbf-8890-adbff2cd42c0966ec4ca-d792-4211-b3e0-4657a90b54326592fbba-f195-4145-b069-43faf57bf7e5 in directory /app/aleph2/data/ttm/master/managed_bucket/import/ready/ is exceeded: limit=255 length=291
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.verifyMaxComponentLength(FSDirectory.java:944)
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.verifyFsLimitsForRename(FSDirRenameOp.java:114)
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.unprotectedRenameTo(FSDirRenameOp.java:189)
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.renameTo(FSDirRenameOp.java:474)
	at org.apache.hadoop.hdfs.server.namenode.FSDirRenameOp.renameToInt(FSDirRenameOp.java:73)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.renameTo(FSNamesystem.java:3661)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.rename(NameNodeRpcServer.java:932)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.rename(ClientNamenodeProtocolServerSideTranslatorPB.java:575)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2151)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2147)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2145)

	at org.apache.hadoop.ipc.Client.call(Client.java:1476)
	at org.apache.hadoop.ipc.Client.call(Client.java:1407)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy13.rename(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.rename(ClientNamenodeProtocolTranslatorPB.java:487)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy14.rename(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.rename(DFSClient.java:1959)
	at org.apache.hadoop.hdfs.DistributedFileSystem.rename(DistributedFileSystem.java:626)
	at com.ikanow.aleph2.analytics.hadoop.assets.BeFileInputReader.nextKeyValue(BeFileInputReader.java:188)
	at com.ikanow.aleph2.analytics.hadoop.assets.Aleph2MultiInputFormatBuilder$Aleph2MultiRecordReader.nextKeyValue(Aleph2MultiInputFormatBuilder.java:180)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:556)
	at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)```

**Comment by Alex-Ikanow** [comment]
Looked into this, the one file was a 2GB JSON file

Seems like what's happening is something like:
* Job dies for some reason (2GB JSON should be fine, everything streams - but eg some misc exception)
* name.UUID gets left in the input ready dir
* next time it gets read, it gets treated like binary, and now we really are in trouble
